name = "FastPriorityQueues"
uuid = "d4e633c3-44a9-41d8-acf9-6b39ae83a07a"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.18"
julia = "1.7"

[extras]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataStructures", "Test"]
